version: 2
machine:
  services:
    -docker
jobs:
  build:
    machine: true
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Service health check
          command: |
              docker run -d --name mysvc blackducksoftware/hub-imageinspector-ws-ubuntu:2.1.3
              sleep 30
              docker exec mysvc curl -i --retry 10 --retry-connrefused http://localhost:9002/health
      #- run:
          #name: Run Detect
          #command: bash <(curl -s https://blackducksoftware.github.io/hub-detect/hub-detect.sh) --detect.docker.image=alpine:latest --detect.hub.signature.scanner.disabled --blackduck.hub.offline.mode=true --blackduck.hub.url=https://prd-int-hub01.dc2.lan --blackduck.hub.username=sysadmin --blackduck.hub.password=blackduck
