version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Run Detect
          command: |
              ##export DETECT_DOCKER_PASSTHROUGH_DOCKER_INSPECTOR_VERSION=6.0.5-SNAPSHOT
              bash <(curl -s https://blackducksoftware.github.io/hub-detect/hub-detect.sh) --detect.docker.image=alpine:latest --detect.hub.signature.scanner.disabled=true --blackduck.hub.offline.mode=true --detect.docker.passthrough.imageinspector.service.start=true --logging.level.com.blackducksoftware.integration=DEBUG --detect.docker.passthrough.shared.dir.path.local=$(pwd)/shared
      - run:
          name: Build failed
          when: on_fail
          command: |
              echo "============================ Ubuntu service log:"
              docker logs ubuntusvc
              echo "============================ Alpine service log:"
              docker logs alpinesvc
