version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Service health check
          command: |
              pwd
              ls -ld .
              mkdir shared
              docker run -d --name alpinesvc -p 8080:8080 blackducksoftware/hub-imageinspector-ws-alpine:2.2.0-SNAPSHOT
              docker run -d --name centossvc -p 8081:8081 blackducksoftware/hub-imageinspector-ws-centos:2.2.0-SNAPSHOT
              docker run -d --name ubuntusvc -p 8082:8082 blackducksoftware/hub-imageinspector-ws-ubuntu:2.2.0-SNAPSHOT
              sleep 30
              docker logs ubuntusvc
              docker ps

              #echo EXECUTING docker exec ubuntusvc curl -i --retry 10 --retry-delay 15 http://localhost:8082/health
              #docker exec ubuntusvc curl -i --retry 10 --retry-delay 15 http://localhost:8082/health

              echo ""; echo EXECUTING curl -i --retry 10 --retry-delay 15 http://localhost:8080/health
              curl -i --retry 10 --retry-delay 15 http://localhost:8080/health

              echo ""; echo EXECUTING curl -i --retry 10 --retry-delay 15 http://localhost:8081/health
              curl -i --retry 10 --retry-delay 15 http://localhost:8081/health

              echo ""; echo EXECUTING curl -i --retry 10 --retry-delay 15 http://localhost:8082/health
              curl -i --retry 10 --retry-delay 15 http://localhost:8082/health
      - run:
          name: Run Detect
          command: |
              export DETECT_DOCKER_PASSTHROUGH_DOCKER_INSPECTOR_VERSION=6.0.5-SNAPSHOT
              env
              bash <(curl -s https://blackducksoftware.github.io/hub-detect/hub-detect.sh) --detect.docker.image=alpine:latest --detect.hub.signature.scanner.disabled=true --blackduck.hub.offline.mode=true --detect.docker.passthrough.imageinspector.service.url=http://localhost:8082 --logging.level.com.blackducksoftware.integration=DEBUG
      - run:
          name: Build failed
          when: on_fail
          command: |
              echo "============================ Ubuntu service log:"
              docker logs ubuntusvc
              echo "============================ Alpine service log:"
              docker logs alpinesvc
