version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Run Detect
          command: |
              bash <(curl -s https://blackducksoftware.github.io/hub-detect/hub-detect.sh) --detect.docker.image=alpine:latest --detect.hub.signature.scanner.disabled=true --blackduck.hub.offline.mode=true --detect.docker.passthrough.imageinspector.service.start=true --logging.level.com.blackducksoftware.integration=DEBUG
